smbportal/api/urls.py
#########################################################################
#
# Copyright 2019, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""URLs for the smb-portal's REST API"""

from django.conf import settings
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from .fcm.api import FCMDeviceAuthorizedViewSet
from rest_framework import routers
from rest_framework.permissions import AllowAny

from badges.api import views as badges_views
from prizes.api import views as prizes_views
from profiles.api.urls import urlpatterns as profiles_urlpatterns
from profiles.api import views as profiles_views
from tracks.api import views as tracks_views
from vehiclemonitor.api import views as vehiclemonitor_views
from vehicles.api import views as vehicles_views

app_name = "api"

router = routers.DefaultRouter()
router.register(
    prefix="my-devices",
    viewset=FCMDeviceAuthorizedViewSet,
    base_name="my-devices"
)
router.register(
    prefix="my-badges",
    viewset=badges_views.MyBadgeViewSet,
    base_name="my-badges"
)
router.register(
    prefix="badges",
    viewset=badges_views.BadgeViewSet,
    base_name="badges"
)
router.register(
    prefix="my-competitions-won",
    viewset=prizes_views.MyCompetitionWonViewSet,
    base_name="my-competitions-won"
)
router.register(
    prefix="my-competitions-current",
    viewset=prizes_views.MyCurrentCompetitionViewSet,
    base_name="my-competitions-current"
)
router.register(
    prefix="my-competitions-available",
    viewset=prizes_views.MyAvailableCompetitionViewSet,
    base_name="my-competitions-available"
)
router.register(
    prefix="competitions",
    viewset=prizes_views.CompetitionViewSet,
    base_name="competitions"
)
router.register(
    prefix="users",
    viewset=profiles_views.SmbUserViewSet,
    base_name="users"
)
router.register(
    prefix="my-segments",
    viewset=tracks_views.MySegmentViewSet,
    base_name="my-segments"
)
router.register(
    prefix="my-tracks",
    viewset=tracks_views.MyTrackViewSet,
    base_name="my-tracks"
)
router.register(
    prefix="tracks",
    viewset=tracks_views.TrackViewSet,
    base_name="tracks"
)
router.register(
    prefix="segments",
    viewset=tracks_views.SegmentViewSet,
    base_name="segments"
)
router.register(
    prefix="my-bike-observations",
    viewset=vehiclemonitor_views.MyBikeObservationViewSet,
    base_name="my-bike-observations"
)
router.register(
    prefix="bike-observations",
    viewset=vehiclemonitor_views.BikeObservationViewSet,
    base_name="bike-observations"
)
router.register(
    prefix="my-bikes",
    viewset=vehicles_views.MyBikeViewSet,
    base_name="my-bikes"
)
router.register(
    prefix="my-tags",
    viewset=vehicles_views.MyPhysicalTagViewSet,
    base_name="my-tags"
)
router.register(
    prefix="my-bike-statuses",
    viewset=vehicles_views.MyBikeStatusViewSet,
    base_name="my-bike-statuses"
)
router.register(
    prefix="bikes",
    viewset=vehicles_views.BikeViewSet,
    base_name="bikes"
)
router.register(
    prefix="bike-statuses",
    viewset=vehicles_views.BikeStatusViewSet,
    base_name="bike-statuses"
)

router.register(
    prefix="tagged-bike",
    viewset=vehicles_views.TaggedBikeViewSet,
    base_name="tagged-bike"
)

router.register(
    prefix="my-tagged-bike",
    viewset=vehicles_views.MyTaggedBikeViewSet,
    base_name="my-tagged-bike"
)

router.register(
    prefix="tags",
    viewset=vehicles_views.PhysicalTagViewSet,
    base_name="tags"
)

schema_view = get_schema_view(
    info=openapi.Info(
        title="",
        default_version="v1",
        description="SaveMyBike Platform API",
        terms_of_service="",
        contact=openapi.Contact(email="info@savemybike.eu"),
        license=openapi.License(name="BSD License"),
    ),
    url="{}/api".format(settings.KEYCLOAK["client_public_uri"]),
    public=False,
    permission_classes=[
        AllowAny,
    ]
)

urlpatterns = router.urls + profiles_urlpatterns + [
    path(
        route=r"swagger/",
        view=schema_view.with_ui("swagger", cache_timeout=None),
        name="schema-swagger-ui",
    ),
]

smbportal/base/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""smbportal URL Configuration"""

from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path(
        route="i18n/",
        view=include("django.conf.urls.i18n")
    ),
    path(
        route="admin/",
        view=admin.site.urls
    ),
    path(
        route="openid/",
        view=include("djangooidc.urls")
    ),
    path(
        route="openid/openid/KeyCloak",
        view=auth_views.login,
        name="login"
    ),
    path(
        route="avatar/",
        view=include("avatar.urls"),
        name="avatar",
    ),
    path(
        route="photologue/",
        view=include("photologue.urls", namespace="photologue")
    ),
    path(
        route="api/",
        view=include("api.urls"),
        name="api",
    ),
    path(
        route="api-auth/",
        view=include("rest_framework.urls", namespace="rest_framework"),
        name="api-auth",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path(
        route="",
        view=views.index,
        name="index"
    ),
    path(
        route="profile/",
        view=include("profiles.urls"),
        name="profile"
    ),
    path(
        route="bikes/",
        view=include("vehicles.urls"),
        name="bikes"
    ),
    path(
        route="observations/",
        view=include("vehiclemonitor.urls"),
        name="observations"
    ),
    path(
        route='privacy_policy/',
        view=TemplateView.as_view(template_name="privacy/privacy_policy.html"),
        name='privacy_policy'
    ),
    path(
        route='dashboard/',
        view=include("dashboard.urls"),
        name='dashboard'
    )
)

smbportal/vehiclemonitor/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.urls import path

from . import views

app_name = "monitor"
urlpatterns = [
    path(
        route="<bike_slug>",
        view=views.BikeObservationListView.as_view(),
        name="list"
    ),
    # path(
    #     route="<bike_pk>/<pk>",
    #     view=views.BikeObservationDetailView.as_view(),
    #     name="detail"
    # ),
]

smbportal/vehicles/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.urls import path

from . import views

app_name = "bikes"
urlpatterns = [
    path(
        route="",
        view=views.BikeListView.as_view(),
        name="list"
    ),
    path(
        route="create",
        view=views.BikeCreateView.as_view(),
        name="create"
    ),
    path(
        route="report-status",
        view=views.BikeStatusCreateView.as_view(),
        name="report-status-no-bike"
    ),
    path(
        route="<slug>",
        view=views.BikeDetailView.as_view(),
        name="detail"
    ),
    path(
        route="<slug>/tag-registration",
        view=views.TagRegistrationTemplateView.as_view(),
        name="tag-registration"
    ),
    path(
        route="<slug>/update",
        view=views.BikeUpdateView.as_view(),
        name="update"
    ),
    path(
        route="<slug>/delete",
        view=views.BikeDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="<slug>/report-status",
        view=views.BikeStatusCreateView.as_view(),
        name="report-status"
    ),
    path(
        route="<slug>/pictures",
        view=views.BikeGalleryDetailView.as_view(),
        name="gallery"
    ),
    path(
        route="<slug>/pictures/upload",
        view=views.BikePictureUploadView.as_view(),
        name="picture-upload"
    ),
    path(
        route="<slug>/pictures/delete",
        view=views.BikePictureDeleteView.as_view(),
        name="pictures-delete"
    ),
]

smbportal/vehicles/models.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

import logging
import uuid

from django.db import models
from django.contrib.gis.db import models as gis_models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.shortcuts import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from photologue.models import Gallery
from photologue.models import Photo
import shortuuid

logger = logging.getLogger(__name__)


class Vehicle(models.Model):
    id = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid.uuid4,
    )
    short_uuid = models.CharField(
        _("short identifier"),
        max_length=8,
        editable=False,
        unique=True,
        null=False
    )
    last_position = models.ForeignKey(
        "tracks.CollectedPoint",
        models.CASCADE,
        verbose_name=_("last position"),
        blank=True,
        null=True
    )

    def save(self, *args, **kwargs):
        if not self.short_uuid:
            self.short_uuid = shortuuid.encode(self.id)[:8]
        return super().save(*args, **kwargs)

    class Meta:
        abstract = True


class BikeManager(models.Manager):

    def create(self, *args, **kwargs):
        """Create instances

        Automatically create a possession state and a gallery whenever a new
        bike is saved

        """

        bike = self.model(
            *args,
            **kwargs
        )
        bike.save()
        status_history = BikeStatus(
            bike=bike,
            lost=False
        )
        status_history.save()
        gallery_title = "Picture gallery for bike {}".format(bike.pk)
        picture_gallery = Gallery.objects.create(
            title=gallery_title,
            slug=slugify(gallery_title),
        )
        bike.picture_gallery = picture_gallery
        bike.save()
        return bike


# TODO: Add custom managers for retrieving stolen bikes and lost bikes
# TODO: Integrate django-photolog for bike picture gallery
class Bike(Vehicle):
    RACING_BIKE = "racing"
    CITY_BIKE = "city"
    MOUNTAIN_BIKE = "mountain"
    FOLDABLE_BIKE = "foldable"

    SINGLE_RING_GEAR = "single ring"
    GROUPSET_UNDER_18_SPEED_GEAR = "groupset below 18 speeds"
    GROUPSET_ABOVE_18_SPEED_GEAR = "groupset above 18 speeds"
    ELECTRIC_GEAR = "electric"

    DISK_BRAKE = "disk"
    CANTILEVER_BRAKE = "cantilever"
    COASTER_BRAKE = "coaster"

    objects = BikeManager()

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="bikes",
        verbose_name=_("owner")
    )
    picture_gallery = models.OneToOneField(
        "photologue.Gallery",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name=_("picture_gallery")
    )
    last_update = models.DateTimeField(
        _("last update"),
        auto_now=True,
        db_column="lastupdate",
    )
    bike_type = models.CharField(
        _("bike type"),
        max_length=20,
        choices=(
            (RACING_BIKE, _("racing")),
            (CITY_BIKE, _("city")),
            (MOUNTAIN_BIKE, _("mountain")),
            (FOLDABLE_BIKE, _("foldable")),
        ),
        default=CITY_BIKE,
    )
    gear = models.CharField(
        _("gear"),
        max_length=50,
        choices=(
            (SINGLE_RING_GEAR, _("single ring")),
            (GROUPSET_UNDER_18_SPEED_GEAR, _("groupset below 18 speeds")),
            (GROUPSET_ABOVE_18_SPEED_GEAR, _("groupset above 18 speeds")),
            (ELECTRIC_GEAR, _("electric")),
        ),
        default=GROUPSET_ABOVE_18_SPEED_GEAR,
    )
    brake = models.CharField(
        _("brake"),
        max_length=30,
        choices=(
            (DISK_BRAKE, _("disk")),
            (CANTILEVER_BRAKE, _("cantilevel")),
            (COASTER_BRAKE, _("coaster")),
        ),
        default=DISK_BRAKE,
    )
    nickname = models.CharField(
        _("bikename"),
        max_length=100
    )
    brand = models.CharField(
        _("brand"),
        max_length=50,
        blank=True
    )
    model = models.CharField(
        _("model"),
        max_length=50,
        blank=True
    )
    color = models.CharField(
        _("color"),
        max_length=100,
        blank=True
    )
    saddle = models.CharField(
        _("saddle"),
        max_length=100,
        blank=True
    )
    has_basket = models.BooleanField(
        _("has basket"),
        default=False
    )
    has_cargo_rack = models.BooleanField(
        _("has cargo rack"),
        default=False
    )
    has_lights = models.BooleanField(
        _("has lights"),
        default=False
    )
    has_bags = models.BooleanField(
        _("has bags"),
        default=False
    )
    other_details = models.TextField(
        _("other details"),
        blank=True
    )

    class Meta:
        unique_together = ("owner", "nickname")
        ordering = [
            "id",
        ]

    def __str__(self):
        return "{0.nickname}".format(self)

    def clean(self):
        max_bikes = settings.SMB_PORTAL.get("max_bikes_per_user", 5)
        if self._state.adding and self.owner.bikes.count() >= max_bikes:
            logger.error("Cannot create a new bike. Limit reached")
            raise ValidationError(
                _("Bikes limit reached. Cannot add more bikes. Delete some "
                  "existing bikes first.")
            )

    def get_absolute_url(self):
        return reverse("bikes:detail", kwargs={"slug": self.short_uuid})

    def get_current_status(self):
        return self.status_history.order_by("-creation_date").first()

    def get_latest_observation(self):
        return self.observations.order_by("-observed_at").first()

    def report_status(self, lost, reporter=None, details=None):
        status_obj = BikeStatus(
            bike=self,
            reporter=reporter if reporter is not None else self.owner,
            lost=lost,
            details=details if details is not None else ""
        )
        status_obj.full_clean()
        status_obj.save()


class BikeStatus(models.Model):
    bike = models.ForeignKey(
        "Bike",
        on_delete=models.CASCADE,
        related_name="status_history",
        verbose_name=_("bike")
    )
    lost = models.BooleanField(
        _("lost"),
        default=False
    )
    creation_date = models.DateTimeField(
        _("creation date"),
        auto_now_add=True
    )
    details = models.TextField(
        _("details"),
        blank=True
    )
    position = gis_models.PointField(
        _("position"),
        null=True,
        blank=True,
        help_text=_("Bike last seen position")
    )

    def __str__(self):
        return "{status}({creation_date})".format(
            status="lost" if self.lost else "with_owner",
            creation_date=self.creation_date
        )

    class Meta:
        ordering = [
            "-creation_date",
        ]


class PhysicalTag(models.Model):
    bike = models.ForeignKey(
        "Bike",
        on_delete=models.CASCADE,
        related_name="tags",
        verbose_name=_("bike")
    )
    epc = models.TextField(
        _("epc"),
        help_text=_("Electronic Product Code"),
        unique=True
    )
    creation_date = models.DateTimeField(
        _("creation date"),
        auto_now_add=True
    )

    class Meta:
        ordering = [
            "creation_date",
        ]


class BikePicture(Photo):

    class Meta:
        proxy = True

    def clean(self):
        max_pictures = settings.SMB_PORTAL.get("max_pictures_per_bike", 5)
        if self._state.adding and self.gallery.photos.count() >= max_pictures:
            logger.error("Cannot upload a new picture. Limit reached")
            raise ValidationError(
                _("Bike pictures limit reached. Cannot add more pictures. "
                  "Delete some existing pictures first.")
            )

smbportal/templates/vehicles/bike_confirm_delete_inner.html
{% load i18n %}
{% load crispy_forms_tags %}

<p>{% blocktrans with nickname=bike.nickname %}Are you sure you want to delete bike <strong>{{ nickname }}</strong>?{% endblocktrans %}</p>
<form id="bikeDeleteForm" method="post" action="{% url 'bikes:delete' slug=bike.short_uuid %}">
    {% csrf_token %}
    {{ form|crispy }}
    {% comment %}
        Form submit is rendered in the modal
    {% endcomment %}
</form>

smbportal/templates/vehicles/bike_create_inner.html
{% load crispy_forms_tags %}

{% crispy form %}

smbportal/templates/vehicles/bike_detail.html
{% extends 'vehicles/base.html' %}

{% load i18n %}
{% load static %}
{% load django_bootstrap_breadcrumbs %}

{% block extra_head %}
    {% comment %}
        Adding the openlayers css and js here since they might be needed if the user chooses to update bike status
    {% endcomment %}
    <link rel="stylesheet" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.1/ol.css">
    <link rel="stylesheet" media="screen" href="{% static 'gis/css/ol3.css' %}">
{% endblock %}

{% block page_title %}{% trans "Bike details" %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb bike.nickname 'bikes:detail' slug=bike.short_uuid %}
{% endblock %}

{% block main %}
    <div class="col-lg-8 col-md-8 order-md-1">
        <h1>{{ bike.nickname }}</h1>
        <div class="gallery-wrapper order-md-4" data-pswp-uid="1">
            <div class="row">
                {% for photo in bike.picture_gallery.photos.all %}
                    <div class="col-md-4 col-sm-6">
                        <div class="gallery-item">
                            <a href="{{ photo.image.url }}" data-size="{{ photo.image.width }}x{{ photo.image.height }}">
                                <img src="{{ photo.get_display_url }}" class="img-thumbnail" alt="{{ photo.title }}">
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <ul class="list-group">
            {% with status=bike.get_current_status %}
                <li class="list-group-item list-group-item-action flex-column align-items-start {% if status.lost %}bg-danger text-white{% else %}bg-success text-white{% endif %}">
                    <div class="d-flex justify-content-between">
                        <h6 class="text-white">{% trans "Current status" %}</h6>
                        <span>{% if status.lost %}{% trans "Lost" %}{% else %}{% trans "With owner" %}{% endif %}</span>
                    </div>
                </li>
            {% endwith %}
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Registration code" %}</h6>
                    <span>{{ bike.short_uuid }}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Bike type" %}</h6>
                    <span>{% blocktrans with bike_type=bike.get_bike_type_display %}{{ bike_type }}{% endblocktrans %}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Gears" %}</h6>
                    <span>{% blocktrans with gear=bike.get_gear_display %}{{ gear }}{% endblocktrans %}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Brakes" %}</h6>
                    <span>{% blocktrans with brakes=bike.get_brake_display %}{{ brakes }}{% endblocktrans %}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Brand" %}</h6>
                    <span>{{ bike.brand }}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Model" %}</h6>
                    <span>{{ bike.model }}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Color" %}</h6>
                    <span>{{ bike.color }}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Saddle" %}</h6>
                    <span>{{ bike.saddle }}</span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Basket" %}</h6>
                    <span><i class="fa {% if bike.has_basket %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Cargo rack" %}</h6>
                    <span><i class="fa {% if bike.has_cargo_rack %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Light" %}</h6>
                    <span><i class="fa {% if bike.has_lights %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Bags" %}</h6>
                    <span><i class="fa {% if bike.has_bags %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "Other details" %}</h6>
                    <p>{{ bike.other_details }}</p>
                </div>
            </li>
            <li class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex justify-content-between">
                    <h6>{% trans "RFID tags" %}</h6>
                    <ul>
                        {% for tag in bike.tags.all %}
                            <li>{{ tag.epc }}</li>
                        {% empty %}
                            <li>{% trans "This bike does not have any tags" %}</li>
                        {% endfor %}
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <div class="col-lg-4 col-md-4 order-md-2 r5_m_t_20 bike-detail-menu">
        <nav class="list-group">
            <a href="https://www.savemybike.eu/prenota-installazione-sensori/" target="_blank" class="list-group-item list-group-item-action"><i class="fa fa-calendar fa-pink-marker"></i> {% trans "Book the RFID installation" %}</a>
            <a href="{% url 'bikes:tag-registration' slug=bike.short_uuid %}" class="list-group-item list-group-item-action"><i class="fa fa-bicycle fa-pink-marker"></i> {% trans "Print bike registry info" %}</a>
            <a href="{% url 'monitor:list' bike_slug=bike.short_uuid %}" class="list-group-item list-group-item-action"><i class="fa fa-map-o fa-pink-marker"></i> {% trans "View bike observations" %}</a>
            <a
                    id="updateBike"
                    data-toggle="modal"
                    data-action-url="{% url 'bikes:update' slug=bike.short_uuid %}"
                    data-primary-button-value="{% trans 'Update bike' %}"
                    data-primary-button-icon="fa fa-pencil-square-o"
                    data-primary-button-classes="btn btn-primary"
                    data-title="{% trans 'Edit bike details' %}"
                    href="#"
                    class="list-group-item list-group-item-action"
            ><i class="fa fa-pencil-square-o fa-pink-marker"></i> {% trans "Edit bike details" %}</a>

            <a href="{% url 'bikes:gallery' slug=bike.short_uuid %}" class="list-group-item list-group-item-action"><i class="fa fa-picture-o fa-pink-marker"></i> {% trans "Manage bike pictures" %}</a>
            <a
                    id="reportBikeStatus"
                    data-toggle="modal"
                    data-action-url="{% url 'bikes:report-status' slug=bike.short_uuid %}"
                    data-primary-button-value="{% trans 'Update bike status' %}"
                    data-primary-button-icon="fa fa-file-text-o"
                    data-primary-button-classes="btn btn-primary"
                    data-title="{% trans 'Update bike status' %}"
                    href="#"
                    class="list-group-item list-group-item-action"
            ><i class="fa fa-file-text-o fa-pink-marker"></i> {% trans "Update bike status" %}</a>
            <a
                    id="deleteBike"
                    data-toggle="modal"
                    data-action-url="{% url 'bikes:delete' slug=bike.short_uuid %}"
                    data-primary-button-value="{% trans 'Delete bike' %}"
                    data-primary-button-icon="fa fa-trash-o"
                    data-primary-button-classes="btn btn-danger"
                    data-title="{% trans 'Delete bike' %}"
                    href="#"
                    class="list-group-item list-group-item-action list-group-item-danger"
            ><i class="fa fa-trash-o"></i> {% trans "Delete bike" %}</a>
        </nav>
    </div>
{% endblock %}

{% block modals %}
    {{ block.super }}
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="pswp__bg"></div>
        <div class="pswp__scroll-wrap">
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>
            <div class="pswp__ui pswp__ui--hidden">
                <div class="pswp__top-bar">
                    <div class="pswp__counter"></div>
                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>
                    <button class="pswp__button pswp__button--share" title="Share"></button>
                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>
                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pswp__share-modal pswp__single-tap pswp__share-modal--hidden">
                    <div class="pswp__share-tooltip"></div>
                </div>
                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button>
                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button>
                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.1/ol.js"></script>
    <script src="{% static 'gis/js/OLMapWidget.js' %}"></script>
    {{ block.super }}
    <script src="{% static 'vehicles/js/bike-detail.js' %}"></script>
{% endblock %}

smbportal/templates/vehicles/bikestatus_create_inner.html
{% load crispy_forms_tags %}
{% crispy form %}