smbportal/api/urls.py
#########################################################################
#
# Copyright 2019, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""URLs for the smb-portal's REST API"""

from django.conf import settings
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from .fcm.api import FCMDeviceAuthorizedViewSet
from rest_framework import routers
from rest_framework.permissions import AllowAny

from badges.api import views as badges_views
from prizes.api import views as prizes_views
from profiles.api.urls import urlpatterns as profiles_urlpatterns
from profiles.api import views as profiles_views
from tracks.api import views as tracks_views
from vehiclemonitor.api import views as vehiclemonitor_views
from vehicles.api import views as vehicles_views

app_name = "api"

router = routers.DefaultRouter()
router.register(
    prefix="my-devices",
    viewset=FCMDeviceAuthorizedViewSet,
    base_name="my-devices"
)
router.register(
    prefix="my-badges",
    viewset=badges_views.MyBadgeViewSet,
    base_name="my-badges"
)
router.register(
    prefix="badges",
    viewset=badges_views.BadgeViewSet,
    base_name="badges"
)
router.register(
    prefix="my-competitions-won",
    viewset=prizes_views.MyCompetitionWonViewSet,
    base_name="my-competitions-won"
)
router.register(
    prefix="my-competitions-current",
    viewset=prizes_views.MyCurrentCompetitionViewSet,
    base_name="my-competitions-current"
)
router.register(
    prefix="my-competitions-available",
    viewset=prizes_views.MyAvailableCompetitionViewSet,
    base_name="my-competitions-available"
)
router.register(
    prefix="competitions",
    viewset=prizes_views.CompetitionViewSet,
    base_name="competitions"
)
router.register(
    prefix="users",
    viewset=profiles_views.SmbUserViewSet,
    base_name="users"
)
router.register(
    prefix="my-segments",
    viewset=tracks_views.MySegmentViewSet,
    base_name="my-segments"
)
router.register(
    prefix="my-tracks",
    viewset=tracks_views.MyTrackViewSet,
    base_name="my-tracks"
)
router.register(
    prefix="tracks",
    viewset=tracks_views.TrackViewSet,
    base_name="tracks"
)
router.register(
    prefix="segments",
    viewset=tracks_views.SegmentViewSet,
    base_name="segments"
)
router.register(
    prefix="my-bike-observations",
    viewset=vehiclemonitor_views.MyBikeObservationViewSet,
    base_name="my-bike-observations"
)
router.register(
    prefix="bike-observations",
    viewset=vehiclemonitor_views.BikeObservationViewSet,
    base_name="bike-observations"
)
router.register(
    prefix="my-bikes",
    viewset=vehicles_views.MyBikeViewSet,
    base_name="my-bikes"
)
router.register(
    prefix="my-tags",
    viewset=vehicles_views.MyPhysicalTagViewSet,
    base_name="my-tags"
)
router.register(
    prefix="my-bike-statuses",
    viewset=vehicles_views.MyBikeStatusViewSet,
    base_name="my-bike-statuses"
)
router.register(
    prefix="bikes",
    viewset=vehicles_views.BikeViewSet,
    base_name="bikes"
)
router.register(
    prefix="bike-statuses",
    viewset=vehicles_views.BikeStatusViewSet,
    base_name="bike-statuses"
)

router.register(
    prefix="tagged-bike",
    viewset=vehicles_views.TaggedBikeViewSet,
    base_name="tagged-bike"
)

router.register(
    prefix="my-tagged-bike",
    viewset=vehicles_views.MyTaggedBikeViewSet,
    base_name="my-tagged-bike"
)

router.register(
    prefix="tags",
    viewset=vehicles_views.PhysicalTagViewSet,
    base_name="tags"
)

schema_view = get_schema_view(
    info=openapi.Info(
        title="",
        default_version="v1",
        description="SaveMyBike Platform API",
        terms_of_service="",
        contact=openapi.Contact(email="info@savemybike.eu"),
        license=openapi.License(name="BSD License"),
    ),
    url="{}/api".format(settings.KEYCLOAK["client_public_uri"]),
    public=False,
    permission_classes=[
        AllowAny,
    ]
)

urlpatterns = router.urls + profiles_urlpatterns + [
    path(
        route=r"swagger/",
        view=schema_view.with_ui("swagger", cache_timeout=None),
        name="schema-swagger-ui",
    ),
]

smbportal/base/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""smbportal URL Configuration"""

from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path(
        route="i18n/",
        view=include("django.conf.urls.i18n")
    ),
    path(
        route="admin/",
        view=admin.site.urls
    ),
    path(
        route="openid/",
        view=include("djangooidc.urls")
    ),
    path(
        route="openid/openid/KeyCloak",
        view=auth_views.login,
        name="login"
    ),
    path(
        route="avatar/",
        view=include("avatar.urls"),
        name="avatar",
    ),
    path(
        route="photologue/",
        view=include("photologue.urls", namespace="photologue")
    ),
    path(
        route="api/",
        view=include("api.urls"),
        name="api",
    ),
    path(
        route="api-auth/",
        view=include("rest_framework.urls", namespace="rest_framework"),
        name="api-auth",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path(
        route="",
        view=views.index,
        name="index"
    ),
    path(
        route="profile/",
        view=include("profiles.urls"),
        name="profile"
    ),
    path(
        route="bikes/",
        view=include("vehicles.urls"),
        name="bikes"
    ),
    path(
        route="observations/",
        view=include("vehiclemonitor.urls"),
        name="observations"
    ),
    path(
        route='privacy_policy/',
        view=TemplateView.as_view(template_name="privacy/privacy_policy.html"),
        name='privacy_policy'
    ),
    path(
        route='dashboard/',
        view=include("dashboard.urls"),
        name='dashboard'
    )
)

smbportal/profiles/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.urls import path

from . import views

app_name = "profile"
urlpatterns = [
    path(
        route="",
        view=views.ProfileUpdateView.as_view(),
        name="update"
    ),
    path(
        route="create",
        view=views.EndUserProfileCreateView.as_view(),
        name="create"
    ),
    path(
        route="create-privileged",
        view=views.PrivilegedUserProfileCreateView.as_view(),
        name="create-privileged"
    ),
    path(
        route="surveys/create",
        view=views.MobilityHabitsSurveyCreateView.as_view(),
        name='create-survey'
    ),
    path(
        route="surveys/<pk>",
        view=views.MobilityHabitsSurveyDetailView.as_view(),
        name='survey'
    ),
]

smbportal/vehicles/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.urls import path

from . import views

app_name = "bikes"
urlpatterns = [
    path(
        route="",
        view=views.BikeListView.as_view(),
        name="list"
    ),
    path(
        route="create",
        view=views.BikeCreateView.as_view(),
        name="create"
    ),
    path(
        route="report-status",
        view=views.BikeStatusCreateView.as_view(),
        name="report-status-no-bike"
    ),
    path(
        route="<slug>",
        view=views.BikeDetailView.as_view(),
        name="detail"
    ),
    path(
        route="<slug>/tag-registration",
        view=views.TagRegistrationTemplateView.as_view(),
        name="tag-registration"
    ),
    path(
        route="<slug>/update",
        view=views.BikeUpdateView.as_view(),
        name="update"
    ),
    path(
        route="<slug>/delete",
        view=views.BikeDeleteView.as_view(),
        name="delete"
    ),
    path(
        route="<slug>/report-status",
        view=views.BikeStatusCreateView.as_view(),
        name="report-status"
    ),
    path(
        route="<slug>/pictures",
        view=views.BikeGalleryDetailView.as_view(),
        name="gallery"
    ),
    path(
        route="<slug>/pictures/upload",
        view=views.BikePictureUploadView.as_view(),
        name="picture-upload"
    ),
    path(
        route="<slug>/pictures/delete",
        view=views.BikePictureDeleteView.as_view(),
        name="pictures-delete"
    ),
]

smbportal/base/views.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render

from profiles import rules

logger = logging.getLogger(__name__)


def index(request):
    user = request.user
    if user.is_authenticated and not rules.has_profile(user):
        messages.warning(
            request,
            "Please complete your profile before continuing to use the portal"
        )
        result = redirect("profile:create")
    elif user.is_authenticated and rules.is_privileged_user(user):
        result = redirect("dashboard:index")
    else:
        result = render(request, "base/home.html")
    return result

smbportal/templates/base/base.html
{% load static %}
{% load i18n %}
{% load avatar_tags %}
{% load django_bootstrap_breadcrumbs %}
{% load base_extras %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Save my Bike</title>
    <!-- Mobile Specific Meta Tag-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Favicon and Apple Icons-->
    <link rel="icon" type="image/png" href="{% static 'base/img/favicon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'base/img/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <!-- Vendor Styles including: Bootstrap, Font Icons, Plugins, etc.-->
    <link rel="stylesheet" media="screen" href="{% static 'base/css/vendor.min.css' %}">
    <!-- Main Template Styles-->
    <link id="mainStyles" rel="stylesheet" media="screen" href="{% static 'base/css/styles.css'%}">
    <script src="{% static 'base/js/modernizr.min.js' %}"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js"></script>-->
    {% block extra_head %}
    {% endblock %}
</head>

<body>
    <!-- NAVBAR-->
    <header class="navbar sticky">
        <div class="site-branding">
            <div class="inner">
                <a class="site-logo" href="{% url 'index' %}">
                    <img src="{% static 'base/img/logo.png' %}" alt="save-my-bike logo">
                </a>
            </div>
        </div>
        <!-- BEGIN MAIN NAVIGATION-->
        <nav class="site-menu">
            {% block main-navigation %}
                <ul>
                    <li id="bikes"><a href="{% url 'bikes:list' %}"><span>{% trans 'Bikes' %}</span></a></li>
                    <li id="reportLost"><a href="{% url 'bikes:report-status-no-bike' %}"><span>{% trans 'Report a lost Bike' %}</span></a></li>
                    <li id="about"><a href="https://www.savemybike.eu" target="_blank"><span>{% trans 'About' %}</span></a></li>
                </ul>
            {% endblock %}
        </nav>
        <!-- END MAIN NAVIGATION-->
        <!-- BEGIN TOOLBAR-->
        <div class="toolbar">
            <div class="inner">
                <div class="tools">
                    <div class="account">
                        <a href="javascript:void(0)"></a>
                        {% if request.user.is_authenticated %}
                            <div class="user-ava">
                                {% avatar user class="rounded-circle img-responsive" %}
                            </div>
                        {% else %}
                            <a href="{% url 'profile:update' %}"></a><i class="icon-head"></i>
                        {% endif %}
                        <ul class="toolbar-dropdown">
                        {% if request.user.is_authenticated %}
                            <li class="sub-menu-user">
                                <div class="user-ava">
                                    {% avatar user class="img-circle img-responsive" id="user_avatar" %}
                                </div>
                                <div class="user-info">
                                    <h6 class="user-name">{{ request.user.first_name|add_str:" "|add_str:request.user.last_name }}</h6>
                                    <span class="text-xs text-muted"></span>
                                </div>
                            </li>
                            <li><a href="{% url 'profile:update' %}"> <i class="icon-head"></i> {% trans 'My Profile' %}</a></li>
                            <li><a href="javascript:void(0)"> <i class="icon-mail"></i> {% trans 'Messages' %}</a></li>
                            {% if request.user.is_staff %}
                                <li><a href="{% url 'admin:index' %}"> <i class="icon-head"></i> {% trans 'Admin area' %}</a></li>
                            {% endif %}
                            <li class="sub-menu-separator"></li>
                            <li><a href="{% url 'logout' %}"> <i class="icon-lock"></i> {% trans 'Logout' %}</a></li>
                        {% else %}
                            <li><a href="{% url 'login'  %}"> <i class="icon-head"></i> {% trans 'Login/Register' %}</a></li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- END TOOLBAR-->
    </header>

    <!-- BEGIN MAIN CONTENT-->
    {% block breadcrumbs %}
        {% clear_breadcrumbs %}
        {% breadcrumb _("Home") 'index' %}
    {% endblock %}

    <div class="offcanvas-wrapper">
        {% block page_header %}
        <div class="page-title m-b-0">
            <div class="container">
                <div class="column">
                    <h1>{% block page_title %}{% endblock %}</h1>
                </div>
                <div class="column">
                    {% render_breadcrumbs %}
                </div>
            </div>
        </div>
        {% endblock %}
        {% if SMB_PORTAL_MAINTENANCE_MESSAGE %}
        <div style="width: 100%; display: table; margin: 10px 0px 10px 0px">
            <div style="display: table-cell;
                        vertical-align: middle;
                        width: 100%;
                        background-color: #dc2106;
                        color: white;
                        text-align: center;
                        height: 200px;
                        font-size: 2em">
                <p style="margin: 0; padding: 0px 50px 0px 50px">E' stata rilasciata una <b>nuova versione dell'app per Android</b>.</p>
                <p><a href="https://play.google.com/store/apps/details?id=it.geosolutions.savemybike" target="_blank" style="color: white; text-decoration: underline">Ti invitiamo a installare la versione aggiornata poiché <b>la precedente non è più supportata</b></a></p>
            </div>
        </div>
        {% endif %}
        <div id="container" class="">
            {% block hero %}{% endblock %}
            <div class="container p-t-60">
               {% if messages %}
                   <div class="row">
                       <div class="col-lg">
                           {% for message in messages %}
                               <div {% if message.tags %}class="alert alert-dismissible fade show text-center margin-bottom-1x {{ message.tags }}"{% endif %}>
                                   <span class="alert-close" data-dismiss="alert"></span>
                                   {{ message }}
                               </div>
                           {% endfor %}
                       </div>
                   </div>
               {% endif %}
               {%  block content  %}
                   <div class="row">
                       {% block main %}{% endblock %}
                   </div>
               {% endblock %}
            </div>
        <!-- BEGIN SITE FOOTER-->
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <!-- About Us-->
                        <section class="footer-widgets widget widget-links widget-light-skin">
                            <span><a href="https://www.savemybike.eu/" target="_blank">SaveMyBike</a> // info@savemybike.eu // <a href="{% url 'privacy_policy' %}">{% blocktrans %}Privacy Policy{% endblocktrans %} </a> // <a href="{% url 'api:schema-swagger-ui' %}">API</a> // <a href="https://www.geo-solutions.it/" target="_blank">Credits</a></span>
                             <a class="social-button shape-circle sb-facebook sb-light-skin" href="https://www.facebook.com/Savemybike-1505927189521211/" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                            <a class="social-button shape-circle sb-instagram sb-light-skin" href="https://www.instagram.com/savemybike.eu/" target="_blank">
                                <i class="fa fa-instagram"></i>
                            </a>
                            <a class="social-button shape-circle sb-pinterest sb-light-skin" href="https://www.pinterest.com/savemybike" target="_blank">
                                <i class="fa fa-pinterest"></i>
                            </a>
                            <a class="social-button shape-circle twitter sb-light-skin" href="https://twitter.com/savemybike_eu" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                            <a class="social-button shape-circle sb-linkedin sb-light-skin" href="https://www.linkedin.com/in/progetto-savemybike-1a531740/" target="_blank">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </section>
                    </div>

                </div>
            </div>
        </footer>
        </div>
        <!-- END SITE FOOTER-->
    </div>
    <!-- END MAIN CONTENT-->

    <!-- BEGIN BACK TO TOP BUTTON-->
    <a class="scroll-to-top-btn" href="javascript:void(0)">
        <i class="icon-arrow-up"></i>
    </a>
    <!-- END BACK TO TOP BUTTON-->
    <!-- Backdrop-->
    <div class="site-backdrop"></div>
    <!-- BEGIN PRELOADER -->
    <!--
    <div id="preloader">
        <div class="inner">
            <span class="loader"></span>
        </div>
    </div>
    -->
    <!-- END PRELOADER -->
    {% block modals %}
        <div id="smbFormModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="smbModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">Modal body</div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
                        <button id="primaryButton" type="submit" class="btn btn-primary"></button>
                    </div>
                </div>
            </div>
        </div>
        <div id="smbDisplayModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="smbDisplayModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">Modal body</div>
                </div>
            </div>
        </div>
    {% endblock modals %}
    <!-- BEGIN CORE JS -->
    <script src="{% static 'base/js/vendor.min.js' %}"></script>
    <script src="{% static 'base/js/scripts.js' %}"></script>
    {% block js %}
    {% endblock %}
    <script type="text/javascript">
        var Tawk_API=Tawk_API||{};
        var Tawk_LoadStart=new Date();
        (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/5b2a2141d0b5a5479681fca2/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
        })();
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <script>
    window.addEventListener("load", function(){
    window.cookieconsent.initialise({
      "palette": {
        "popup": {
          "background": "#3c404d",
          "text": "#d6d6d6"
        },
        "button": {
          "background": "#F51DAF"
        }
      },
      "position": "top",
      "content": {
        "message": "{% blocktrans %}We use cookies to help make SaveMyBike better. By visiting this site, you agree to our cookie policy{% endblocktrans %}.",
        "dismiss": "{% blocktrans %}Got it!{% endblocktrans %}",
        "link": "{% blocktrans %}Privacy Policy{% endblocktrans %}",
        "href": "{% url 'privacy_policy' %}"
      }
    })});
    </script>
</body>
</html>

smbportal/templates/base/breadcrumbs.html
<ul class="breadcrumbs">
    {% for url, label in breadcrumbs %}
        <li>
            {% ifnotequal forloop.counter breadcrumbs_total %}
                <a href="{{ url }}">{{ label|safe }}</a>
            {% else %}
                {{ label|safe }}
            {% endifnotequal %}
        </li>
        {% if not forloop.last %}
            <li class="separator">&nbsp;</li>
        {% endif %}
    {% endfor %}
</ul>

smbportal/templates/base/home.html
{% extends 'base/base.html' %}

{% load static %}
{% load i18n %}

{% block page_header %}{% endblock %}

{% block hero %}
<section class="hero-slider" style="background-image: url({% static 'base/img/sfondo-bus-sx.jpg' %});">
                <div class="owl-carousel large-controls dots-inside"
                     data-owl-carousel="{ 'nav': true, 'dots': true, 'loop': true, 'autoplay': true, 'autoplayTimeout': 7000 }">
                    <div class="item">
                        <div class="container padding-top-3x">
                            <div class="row justify-content-center align-items-center">
                                <div class="col-lg-10 col-md-6 padding-bottom-2x text-md-left text-center">
                                    <div class="from-bottom">
                                        <div class="h1 main-text force-white text-body text-normal mb-2 pt-1">
                                            {% blocktrans %} Welcome on Good_Go! {% endblocktrans %}
                                        </div>
                                        <div class="h1 text-body force-white text-normal mb-4 pb-1">
                                            {% blocktrans %}The mobility game that rewards{% endblocktrans %}.
                                        </div>
                                        <div class="h1 text-body force-white text-normal mb-4 pb-1" style="font-size: 40px">
                                            <a href="{% url 'login'  %}">Iscriviti</a>, <a href="{% url 'bikes:list' %}">Registra la tua bici</a> e inizia a registrare i tuoi percorsi!
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                   <div class="item">
                        <div class="container padding-top-3x">
                            <div class="row justify-content-center align-items-center">
                                <div class="col-lg-10 col-md-6 padding-bottom-2x text-md-left text-center">
                                    <div class="from-bottom">
                                        <div class="h1 main-text force-white text-body text-normal mb-2 pt-1">
                                            SaveMyBike
                                        </div>
                                        <div class="h1 text-body force-white text-normal mb-1">
                                            {% blocktrans %}Protect your bikes{% endblocktrans %}.
                                        </div>
                                        <div class="h1 text-body force-white text-normal mb-4 pb-1">
                                            {% blocktrans %}Request the RFID sensors to identify and localize them{% endblocktrans %}.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
{% endblock %}

{% block main %}
<div class="col-md-12 margin-bottom-2x">
    <div class="row">
        <div class="col-lg-12 margin-bottom-2x">
            <div class="card border-primary text-center mb-3" style="border-color: #20c0ce !important">
                <div class="card-body">
                    <h4 class="card-title"><span style="font-size: 1.2em; color: #606975">{% blocktrans %}The SaveMyBike User Guide{% endblocktrans %}</span></h4>
                    <p class="card-text"><span style="font-size: 1.1em">{% blocktrans %}<a href="{{ MEDIA_URL }}docs/Manuale_SaveMyBike_v2.pdf" target="_blank"><b>Download</b></a> the document that will guide you through the registration process and first steps on the SaveMyBike Platform{% endblocktrans %}.</span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 margin-bottom-2x">
            <div class="card text-center bg_svg_green text-white">
                <div class="card-body">
                    <h4 class="card-title align-items-center d-flex justify-content-center">{% trans 'Bikes' %}</h4>
                    <p class="card-text align-items-center d-flex justify-content-center">
                        {% blocktrans %} Register new Bikes, update information about your bikes and delete bikes from the system. {% endblocktrans %}
                    </p>
                    <a class="btn btn-block btn-primary" href="{% url 'bikes:list' %}" style="display:inline-block; width:200px">{% trans 'Bikes' %}</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 margin-bottom-2x">
            <div class="card text-center bg_svg_green text-white">
                <div class="card-body">
                    <h4 class="card-title align-items-center d-flex justify-content-center">{% trans 'Sensors' %}</h4>
                    <p class="card-text align-items-center d-flex justify-content-center">
                        {% blocktrans %}Want protection? Add rfid support to your bikes here{% endblocktrans %}
                    </p>
                    <a class="btn btn-block btn-primary" href="https://www.savemybike.eu/prenota-installazione-sensori/" target="_blank"  style="display:inline-block; width:200px">{% trans 'Book your sensor' %}!</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 margin-bottom-2x">
            <div class="card text-center bg_svg_grey">
                <div class="card-body">
                    <h4 class="card-title align-items-center d-flex justify-content-center">{% trans 'Activity' %}</h4>
                    <p class="card-text align-items-center d-flex justify-content-center">
                        {% blocktrans %}View your tracks, calculate your gas emissions credits and the health impacts of cycling{% endblocktrans %}.
                    </p>
                    <a class="btn btn-block btn-secondary" disabled href="javascript:void(0)">{% trans 'Coming soon' %}</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 margin-bottom-2x">
            <div class="card text-center bg_svg_grey">
                <div class="card-body">
                    <h4 class="card-title align-items-center d-flex justify-content-center">{% trans 'Badges' %}</h4>
                    <p class="card-text align-items-center d-flex justify-content-center">
                        {% blocktrans %}View all your Badges, the ones you've unlocked and ones you need to get.{% endblocktrans %}
                    </p>
                    <a class="btn btn-block btn-secondary" disabled href="javascript:void(0)">{% trans 'Coming soon' %}</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 margin-bottom-2x">
            <div class="card text-center bg_svg_grey">
                <div class="card-body">
                    <h4 class="card-title align-items-center d-flex justify-content-center">{% trans 'Prizes' %}</h4>
                    <p class="card-text align-items-center d-flex justify-content-center">
                        {% blocktrans %} View all the prizes you can available in your city.{% endblocktrans %}
                    </p>
                    <a class="btn btn-block btn-secondary" disabled href="javascript:void(0)">{% trans 'Coming soon' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
   
{% endblock %}
{% block js %}


{% endblock %}