smbportal/api/urls.py
#########################################################################
#
# Copyright 2019, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""URLs for the smb-portal's REST API"""

from django.conf import settings
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from .fcm.api import FCMDeviceAuthorizedViewSet
from rest_framework import routers
from rest_framework.permissions import AllowAny

from badges.api import views as badges_views
from prizes.api import views as prizes_views
from profiles.api.urls import urlpatterns as profiles_urlpatterns
from profiles.api import views as profiles_views
from tracks.api import views as tracks_views
from vehiclemonitor.api import views as vehiclemonitor_views
from vehicles.api import views as vehicles_views

app_name = "api"

router = routers.DefaultRouter()
router.register(
    prefix="my-devices",
    viewset=FCMDeviceAuthorizedViewSet,
    base_name="my-devices"
)
router.register(
    prefix="my-badges",
    viewset=badges_views.MyBadgeViewSet,
    base_name="my-badges"
)
router.register(
    prefix="badges",
    viewset=badges_views.BadgeViewSet,
    base_name="badges"
)
router.register(
    prefix="my-competitions-won",
    viewset=prizes_views.MyCompetitionWonViewSet,
    base_name="my-competitions-won"
)
router.register(
    prefix="my-competitions-current",
    viewset=prizes_views.MyCurrentCompetitionViewSet,
    base_name="my-competitions-current"
)
router.register(
    prefix="my-competitions-available",
    viewset=prizes_views.MyAvailableCompetitionViewSet,
    base_name="my-competitions-available"
)
router.register(
    prefix="competitions",
    viewset=prizes_views.CompetitionViewSet,
    base_name="competitions"
)
router.register(
    prefix="users",
    viewset=profiles_views.SmbUserViewSet,
    base_name="users"
)
router.register(
    prefix="my-segments",
    viewset=tracks_views.MySegmentViewSet,
    base_name="my-segments"
)
router.register(
    prefix="my-tracks",
    viewset=tracks_views.MyTrackViewSet,
    base_name="my-tracks"
)
router.register(
    prefix="tracks",
    viewset=tracks_views.TrackViewSet,
    base_name="tracks"
)
router.register(
    prefix="segments",
    viewset=tracks_views.SegmentViewSet,
    base_name="segments"
)
router.register(
    prefix="my-bike-observations",
    viewset=vehiclemonitor_views.MyBikeObservationViewSet,
    base_name="my-bike-observations"
)
router.register(
    prefix="bike-observations",
    viewset=vehiclemonitor_views.BikeObservationViewSet,
    base_name="bike-observations"
)
router.register(
    prefix="my-bikes",
    viewset=vehicles_views.MyBikeViewSet,
    base_name="my-bikes"
)
router.register(
    prefix="my-tags",
    viewset=vehicles_views.MyPhysicalTagViewSet,
    base_name="my-tags"
)
router.register(
    prefix="my-bike-statuses",
    viewset=vehicles_views.MyBikeStatusViewSet,
    base_name="my-bike-statuses"
)
router.register(
    prefix="bikes",
    viewset=vehicles_views.BikeViewSet,
    base_name="bikes"
)
router.register(
    prefix="bike-statuses",
    viewset=vehicles_views.BikeStatusViewSet,
    base_name="bike-statuses"
)

router.register(
    prefix="tagged-bike",
    viewset=vehicles_views.TaggedBikeViewSet,
    base_name="tagged-bike"
)

router.register(
    prefix="my-tagged-bike",
    viewset=vehicles_views.MyTaggedBikeViewSet,
    base_name="my-tagged-bike"
)

router.register(
    prefix="tags",
    viewset=vehicles_views.PhysicalTagViewSet,
    base_name="tags"
)

schema_view = get_schema_view(
    info=openapi.Info(
        title="",
        default_version="v1",
        description="SaveMyBike Platform API",
        terms_of_service="",
        contact=openapi.Contact(email="info@savemybike.eu"),
        license=openapi.License(name="BSD License"),
    ),
    url="{}/api".format(settings.KEYCLOAK["client_public_uri"]),
    public=False,
    permission_classes=[
        AllowAny,
    ]
)

urlpatterns = router.urls + profiles_urlpatterns + [
    path(
        route=r"swagger/",
        view=schema_view.with_ui("swagger", cache_timeout=None),
        name="schema-swagger-ui",
    ),
]

smbportal/base/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""smbportal URL Configuration"""

from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path(
        route="i18n/",
        view=include("django.conf.urls.i18n")
    ),
    path(
        route="admin/",
        view=admin.site.urls
    ),
    path(
        route="openid/",
        view=include("djangooidc.urls")
    ),
    path(
        route="openid/openid/KeyCloak",
        view=auth_views.login,
        name="login"
    ),
    path(
        route="avatar/",
        view=include("avatar.urls"),
        name="avatar",
    ),
    path(
        route="photologue/",
        view=include("photologue.urls", namespace="photologue")
    ),
    path(
        route="api/",
        view=include("api.urls"),
        name="api",
    ),
    path(
        route="api-auth/",
        view=include("rest_framework.urls", namespace="rest_framework"),
        name="api-auth",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path(
        route="",
        view=views.index,
        name="index"
    ),
    path(
        route="profile/",
        view=include("profiles.urls"),
        name="profile"
    ),
    path(
        route="bikes/",
        view=include("vehicles.urls"),
        name="bikes"
    ),
    path(
        route="observations/",
        view=include("vehiclemonitor.urls"),
        name="observations"
    ),
    path(
        route='privacy_policy/',
        view=TemplateView.as_view(template_name="privacy/privacy_policy.html"),
        name='privacy_policy'
    ),
    path(
        route='dashboard/',
        view=include("dashboard.urls"),
        name='dashboard'
    )
)

smbportal/profiles/api/urls.py
#########################################################################
#
# Copyright 2019, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

"""URLs for the smb-portal's REST API"""

from django.urls import path

from . import views

urlpatterns = [
    path(
        route="my-user",
        view=views.MyUserViewSet.as_view(
            actions={
                "get": "retrieve",
                "patch": "partial_update",
                "put": "update",
            }
        ),
        name="my-user"
    )
]

smbportal/profiles/urls.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

from django.urls import path

from . import views

app_name = "profile"
urlpatterns = [
    path(
        route="",
        view=views.ProfileUpdateView.as_view(),
        name="update"
    ),
    path(
        route="create",
        view=views.EndUserProfileCreateView.as_view(),
        name="create"
    ),
    path(
        route="create-privileged",
        view=views.PrivilegedUserProfileCreateView.as_view(),
        name="create-privileged"
    ),
    path(
        route="surveys/create",
        view=views.MobilityHabitsSurveyCreateView.as_view(),
        name='create-survey'
    ),
    path(
        route="surveys/<pk>",
        view=views.MobilityHabitsSurveyDetailView.as_view(),
        name='survey'
    ),
]

smbportal/base/views.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

import logging

from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render

from profiles import rules

logger = logging.getLogger(__name__)


def index(request):
    user = request.user
    if user.is_authenticated and not rules.has_profile(user):
        messages.warning(
            request,
            "Please complete your profile before continuing to use the portal"
        )
        result = redirect("profile:create")
    elif user.is_authenticated and rules.is_privileged_user(user):
        result = redirect("dashboard:index")
    else:
        result = render(request, "base/home.html")
    return result

smbportal/profiles/api/views.py
#########################################################################
#
# Copyright 2018, GeoSolutions Sas.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
#########################################################################

import logging

from django.conf import settings
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action
from rest_framework import mixins
from rest_framework import viewsets
from rest_framework import status
from rest_framework.response import Response
from rest_framework.settings import api_settings

from keycloakauth import utils
from keycloakauth.keycloakadmin import get_manager

from .. import models
from . import serializers
from . import pagination

logger = logging.getLogger(__name__)


# FIXME: account for different user profiles
class MyUserViewSet(mixins.RetrieveModelMixin, mixins.UpdateModelMixin,
                    viewsets.GenericViewSet):
    serializer_class = serializers.MyUserSerializer
    required_permissions = (
        "profiles.is_authenticated",
    )

    def get_object(self):
        user = self.request.user
        self.check_object_permissions(self.request, obj=user.profile)
        return user

    def perform_update(self, serializer):
        """Save any modifications to the user object

        In case of profile generation, be sure to communicate with keycloak
        in order to setup correct group memberships

        """

        user = serializer.save()
        _update_group_memberships(user)


class SmbUserViewSet(mixins.ListModelMixin, mixins.RetrieveModelMixin,
                     mixins.DestroyModelMixin, viewsets.GenericViewSet):
    serializer_class = serializers.SmbUserSerializer
    queryset = models.SmbUser.objects.all()
    required_permissions = (
        "profiles.can_list_users",
        "profiles.can_delete_user",
    )
    filter_backends = (
        DjangoFilterBackend,
    )
    filter_fields = (
        "email",
        "username",
    )
    lookup_field = "uuid"
    pagination_class = pagination.SmbUserDumpPageNumberPagination

    def get_object(self):
        obj = self.get_queryset().get(keycloak__UID=self.kwargs["uuid"])
        self.check_object_permissions(self.request, obj)
        return obj

    @action(detail=True)
    def single_dump(self, request, uuid=None):
        user = self.get_object()
        serializer = serializers.UserDumpSerializer(
            instance=user,
            context={"request": request}
        )
        return Response(serializer.data)

    @action(detail=False)
    def dump(self, request):
        qs = self.filter_queryset(self.get_queryset())
        paginated_qs = self.paginate_queryset(qs)
        serializer = serializers.UserDumpSerializer(
            instance=paginated_qs,
            many=True,
            context=self.get_serializer_context(),
        )
        return self.get_paginated_response(serializer.data)

    def perform_destroy(self, instance):
        manager = get_manager(
            settings.KEYCLOAK["base_url"],
            settings.KEYCLOAK["realm"],
            settings.KEYCLOAK["client_id"],
            settings.KEYCLOAK["admin_username"],
            settings.KEYCLOAK["admin_password"],
        )
        utils.delete_user(
            instance.username,
            manager
        )

    @action(methods=["POST"], detail=False)
    def create_end_user(self, request):
        """Create a new user with the `end user` profile.

        The user is created both on the portal and on keycloak

        """

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = self.perform_create_end_user(serializer)
        output_serializer = self.get_serializer_class()(
            instance=user,
            context={"request": request}
        )
        return Response(
            output_serializer.data,
            status=status.HTTP_201_CREATED,
            headers=self.get_success_headers(output_serializer.data)
        )

    def perform_create_end_user(self, serializer):
        group_path = settings.KEYCLOAK[
            "group_mappings"][settings.END_USER_PROFILE][0]
        manager = get_manager(
            settings.KEYCLOAK["base_url"],
            settings.KEYCLOAK["realm"],
            settings.KEYCLOAK["client_id"],
            settings.KEYCLOAK["admin_username"],
            settings.KEYCLOAK["admin_password"],
        )
        user = utils.create_user(
            username=serializer.validated_data.get("username"),
            email=serializer.validated_data.get("email"),
            password=serializer.validated_data.get("password"),
            group_path=group_path,
            keycloak_manager=manager,
            profile_model=models.EndUserProfile
        )
        return user

    def get_success_headers(self, data):
        try:
            return {"Location": str(data[api_settings.URL_FIELD_NAME])}
        except (TypeError, KeyError):
            return {}


def _update_group_memberships(user):
    manager = get_manager(
        settings.KEYCLOAK["base_url"],
        settings.KEYCLOAK["realm"],
        settings.KEYCLOAK["client_id"],
        settings.KEYCLOAK["admin_username"],
        settings.KEYCLOAK["admin_password"],
    )
    user_groups = manager.get_user_groups(user.keycloak.UID)
    logger.debug("updating user group memberships...")
    profile_name = (user.profile.__class__.__name__.lower() if
                    user.profile is not None else None)
    keycloak_group_name = {
        "enduserprofile": settings.END_USER_PROFILE,
        "privilegeduserprofile": settings.PRIVILEGED_USER_PROFILE,
    }.get(profile_name or "")
    utils.update_user_groups(
        user=user,
        user_profile=keycloak_group_name,
        current_keycloak_groups=[g["name"] for g in user_groups]
    )

smbportal/templates/profiles/base.html
{% extends "base/base.html" %}

{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("profile") 'profile:update' %}
{% endblock %}

smbportal/templates/profiles/enduserprofile_create.html
{% extends 'profiles/base.html' %}

{% load i18n %}
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}{% trans "Complete profile" %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("complete profile") 'profile:create' %}
{% endblock %}

{% block content %}
    <div id="container">
        <div class="container p-t-60">
            <div class="row">
                <div class="col-lg-2">
                    <div class="user-info">
                        <div class="user-avatar">
                            <a class="edit-avatar" href="{% url 'avatar_change' %}"><i class="fa fa-pencil-square-o"></i></a>
                            {% avatar user class="rounded-circle" %}
                        </div>
                        <div class="user-data">
                            <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                            <span>
                                <i class="fa fa-user-o"></i> {{ user.username }}<br>
                                <i class="fa fa-envelope-o"></i> {{ user.email }}
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10">
                    <form method="post">
                        {% csrf_token %}
                        {{ user_form|crispy }}
                        {{ form|crispy }}
                        <h4>{% trans "Mobility Survey" %}</h4>
                        <p>{% trans "Please complete this short survey as a final step for creating your profile" %}</p>
                        {{ mobility_form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg">{% trans "Save" %}</button>
                    </form>
                    {% url "profile:create-privileged" as privileged_url %}
                    <p>{% blocktrans %}You can also <a href="{{ privileged_url }}">register as a different user type{% endblocktrans %}</a></p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'profiles/js/profile-create.js' %}"></script>
{% endblock %}

smbportal/templates/profiles/enduserprofile_update.html
{% extends 'profiles/base.html' %}

{% load i18n %}
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}{% trans "Your profile" %}{% endblock %}

{% block main %}
    <div class="col-lg-4">
        <div class="user-info">
            <div class="user-avatar">
                <a class="edit-avatar" href="{% url 'avatar_change' %}"><i class="fa fa-pencil-square-o"></i></a>
                {% avatar user 150 class="rounded-circle" %}
            </div>
            <div class="user-data">
                <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                <span>
                    <i class="fa fa-user-o"></i> {{ user.username }}<br>
                    <i class="fa fa-envelope-o"></i> {{ user.email }}
                </span>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <form method="post">
            {% csrf_token %}
            {{ user_form|crispy }}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        </form>
        {% if enduserprofile.mobility_habits_surveys %}
            <h4 class="mt-5">{% trans "Mobility surveys" %}</h4>
            <div class="list-group">
                {% for survey in enduserprofile.mobility_habits_surveys.all %}
                    <a
                            class="list-group-item list-group-item-action"
                            name="showMobilitySurvey"
                            href="#smbDisplayModal"
                            data-contents-url="{% url 'profile:survey' pk=survey.pk %}"
                            data-toggle="modal"
                            data-title="{% trans 'Mobility survey' %} / {{ survey.date_answered|date:'j F Y' }}"
                    >{{ survey.date_answered|date:'l j F Y' }}</a>
                {% endfor %}
            </div>
            <a class="btn btn-secondary btn-sm" href="{% url 'profile:create-survey' %}">{% trans "Answer mobility survey again" %}</a>
        {% endif %}
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'base/js/smb-utils.js' %}"></script>
    <script src="{% static 'profiles/js/profile-update.js' %}"></script>
{% endblock %}

smbportal/templates/profiles/mobilityhabitssurvey_create.html
{% extends 'profiles/base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("new survey") 'profile:survey' pk=survey.pk %}
{% endblock %}

{% block page_title %}{% trans "New mobility survey" %}{% endblock %}

{% block main %}
    <div class="col-lg-12">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-primary btn-lg">{% trans "Save" %}</button>
        </form>
    </div>
{% endblock %}

smbportal/templates/profiles/mobilityhabitssurvey_detail_inner.html
{% load i18n %}

<ul class="list-group">
    <li class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-between">
            <h6>{% trans 'Bicycle usage' %}</h6>
            <span>{% blocktrans with bicycle_usage=survey.get_bicycle_usage_display %}{{ bicycle_usage }}{% endblocktrans %}</span>
        </div>
    </li>
    <li class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-between">
            <h6>{% trans 'Public transport usage' %}</h6>
            <span>{% blocktrans with public_transport_usage=survey.get_public_transport_usage_display %}{{ public_transport_usage }}{% endblocktrans %}</span>
        </div>
    </li>
    <li class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-between">
            <h6>{% trans 'Uses bike sharing services' %}</h6>
            <span><i class="fa {% if survey.uses_bike_sharing_services %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
        </div>
    </li>
    <li class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-between">
            <h6>{% trans 'Uses electric car sharing services' %}</h6>
            <span><i class="fa {% if survey.uses_electrical_car_sharing_services %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
        </div>
    </li>
    <li class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-between">
            <h6>{% trans 'Uses fuel car sharing services' %}</h6>
            <span><i class="fa {% if survey.uses_fuel_car_sharing_services %}fa-check-square{% else %}fa-square-o{% endif %}"></i></span>
        </div>
    </li>
</ul>

smbportal/templates/profiles/privilegeduserprofile_create.html
{% extends 'profiles/base.html' %}

{% load i18n %}
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}{% trans "Complete profile - Privileged user" %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb _("complete profile privileged user") 'profile:create' %}
{% endblock %}

{% block main %}
    <div class="col-lg-2">
        <div class="user-info">
            <div class="user-avatar">
                <a class="edit-avatar" href="{% url 'avatar_change' %}"><i class="fa fa-pencil-square-o"></i></a>
                {% avatar user class="rounded-circle" %}
            </div>
            <div class="user-data">
                <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                <span>
                    <i class="fa fa-user-o"></i> {{ user.username }}<br>
                    <i class="fa fa-envelope-o"></i> {{ user.email }}
                </span>
            </div>
        </div>
    </div>
    <div class="col-lg-10">
        <div class="col-lg">
            <div class="card text-white bg-info text-center mb-3">
                <div class="card-body">
                    <h4 class="card-title">{% trans "Note" %}</h4>
                    <p class="card-text">{% blocktrans %}Registering as a privileged user requires manual authorization from one of the platform's administrators. Your application will be moderated and you will be notified via e-mail. Until then you will not be able to use the portal{% endblocktrans %}</p>
                </div>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ user_form|crispy }}
            {{ form|crispy }}
            <a href="{% url 'profile:create' %}" class="btn btn-outline-secondary btn-lg"><i class="fa fa-hand-o-left"></i> {% trans "Go back" %}</a>
            <button type="submit" class="btn btn-primary">{% trans "Register as privileged user" %}</button>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'profiles/js/profile-create.js' %}"></script>
{% endblock %}

smbportal/templates/profiles/privilegeduserprofile_update.html
{% extends 'profiles/base.html' %}

{% load i18n %}
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block page_title %}{% trans "Your profile" %}{% endblock %}

{% block main %}
    <div class="col-lg-4">
        <div class="user-info">
            <div class="user-avatar">
                <a class="edit-avatar" href="{% url 'avatar_change' %}"><i class="fa fa-pencil-square-o"></i></a>
                {% avatar user 150 class="rounded-circle" %}
            </div>
            <div class="user-data">
                <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                <span>
                    <i class="fa fa-user-o"></i> {{ user.username }}<br>
                    <i class="fa fa-envelope-o"></i> {{ user.email }}
                </span>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <form method="post">
            {% csrf_token %}
            {{ user_form|crispy }}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
        </form>
    </div>
{% endblock %}